<div class="grid_3">
    <div class="moduletable  ml box pdb10 bgw">
        <div class="m-title">
            <h3>Danh mục sản phẩm</h3>

            <div class="modulcontent">
                <ul class="menu dotx">
                    <li class="item-492"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=83&amp;Itemid=492&amp;lang=vi">Ống
                            uPVC</a></li>
                    <li class="item-493"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=84&amp;Itemid=493&amp;lang=vi">Ống
                            HDPE</a></li>
                    <li class="item-658"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=319&amp;Itemid=658&amp;lang=vi">Ống
                            PPR</a></li>
                    <li class="item-494 deeper parent"><a
                            href="/index.php?option=com_adsmanager&amp;view=list&amp;catid=9&amp;Itemid=494&amp;lang=vi">Phụ
                            kiện uPVC</a>
                        <ul>
                            <li class="item-636"><a
                                    href="/index.php?option=com_adsmanager&amp;view=list&amp;catid=34&amp;Itemid=636&amp;lang=vi">Tiêu
                                    Chuẩn ASTM</a></li>
                            <li class="item-650"><a
                                    href="/index.php?option=com_adsmanager&amp;view=list&amp;catid=28&amp;Itemid=650&amp;lang=vi">Tiêu
                                    Chuẩn ISO</a></li>
                        </ul>
                    </li>
                    <li class="item-597"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=318&amp;Itemid=597&amp;lang=vi">Phụ
                            kiện HDPE</a></li>
                    <li class="item-656"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=321&amp;Itemid=656&amp;lang=vi">Phụ
                            kiện PPR</a></li>
                    <li class="item-598"><a
                            href="/index.php?option=com_adsmanager&amp;view=list&amp;catid=22&amp;Itemid=598&amp;lang=vi">Phụ
                            kiện khác</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="moduletable  ml top15">
        <div class="m-title">
            <h3>Thành tựu nổi bật</h3>

            <div class="modulcontent">
                <script language="JavaScript1.2">
                    var IHRSS_WIDTH = "215px";
                    var IHRSS_HEIGHT = "280px";
                    var IHRSS_SPEED = 1;
                    var IHRSS_BGCOLOR = "#FFFFFF";
                    var IHRSS_SLIDESRARRAY = new Array();
                    var IHRSS_FINALSLIDE = '';
                    IHRSS_SLIDESRARRAY[0] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//T101.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[1] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t161.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[2] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t01.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[3] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//T100.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[4] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//1002.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[5] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t141.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[6] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//1001.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[7] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t171.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[8] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//T10.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[9] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t121.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[10] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//1003.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[11] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t131.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[12] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t181.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[13] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t991.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[14] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//1000.jpg" /></a>';
                    var IHRSS_IMGGAP = " ";
                    var IHRSS_PIXELGAP = 5;
                </script>
                <script
                    src="/modules/mod_horizontal_scrolling_slideshow/tmpl/mod_horizontal_scrolling_slideshow.js"
                    type="text/javascript"></script>
                        <span id="temp" style="visibility:hidden;position:absolute;top:-100px;left:-9000px"><nobr><a
                                    href="#"><img src="http://nhuadenhat.vn/images/bangkhen//T101.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t161.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t01.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//T100.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//1002.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t141.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//1001.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t171.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//T10.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t121.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//1003.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t131.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t181.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t991.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//1000.jpg"></a></nobr></span>
                <table border="0" cellspacing="0" cellpadding="0">
                    <tbody>
                    <tr>
                        <td>
                            <div style="position:relative;width:215px;height:280px;overflow:hidden">
                                <div style="position:absolute;width:215px;height:280px;background-color:#FFFFFF"
                                     onmouseover="copyspeed=0" onmouseout="copyspeed=IHRSS_SPEED">
                                    <div id="test2" style="position: absolute; left: -371px; top: 0px;">
                                        <nobr><a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T101.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t161.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t01.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T100.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1002.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t141.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1001.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t171.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T10.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t121.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1003.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t131.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t181.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t991.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1000.jpg"></a>
                                        </nobr>
                                    </div>
                                    <div id="test3" style="position: absolute; left: 2701px; top: 0px;">
                                        <nobr><a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T101.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t161.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t01.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T100.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1002.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t141.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1001.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t171.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T10.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t121.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1003.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t131.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t181.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t991.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1000.jpg"></a>
                                        </nobr>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="moduletable  ml pdb10">
        <div class="m-title">
            <h3>Tin tức</h3>

            <div class="modulcontent">
                <ul class="menu dotx">
                    <li class="item-507"><a
                            href="/index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=110&amp;Itemid=507&amp;lang=vi">Tin
                            tức nội bộ</a></li>
                    <li class="item-508"><a
                            href="/index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=111&amp;Itemid=508&amp;lang=vi">Tin
                            tức báo chí</a></li>
                    <li class="item-509"><a
                            href="/index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=112&amp;Itemid=509&amp;lang=vi">Bài
                            viết nghiên cứu</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
&nbsp;
<div class="grid_9 fix-right-content">
    &nbsp;
    <div class=" bgw">
        <div id="system-message-container">
        </div>
        <div class="blog">
            <div class="items-leading" id="list-news">
                <script>
                    $(document).ready(function () {
                        getNews();
                    });
                </script>
            </div>

        </div>

    </div>

</div>