<h2>
    <a href="#"><?=$this->item['title']?></a>
</h2>

<ul class="actions">
    <li class="print-icon">
        <a href="/index.php?option=com_content&amp;view=article&amp;id=90:vietbuild1&amp;catid=110&amp;lang=vi&amp;Itemid=588&amp;tmpl=component&amp;print=1&amp;layout=default&amp;page=" title="In bài này" onclick="window.open(this.href,'win2','status=no,toolbar=no,scrollbars=yes,titlebar=no,menubar=no,resizable=yes,width=640,height=480,directories=no,location=no'); return false;" rel="nofollow"><img src="/media/system/images/printButton.png" alt="In bài này"></a>		</li>
    <li class="email-icon">
        <a href="/index.php?option=com_mailto&amp;tmpl=component&amp;template=templatename&amp;link=25ad03e4ecfd36760511f17c5edaeca2d71b57f6&amp;lang=vi" title="Gửi Email bài này" onclick="window.open(this.href,'win2','width=400,height=350,menubar=yes,resizable=yes'); return false;"><img src="/media/system/images/emailButton.png" alt="Gửi Email bài này"></a>		</li>
</ul>

<?=$this->item['introtext']?>

<p class="readmore">
    <a href="/index.php?option=com_content&amp;view=article&amp;id=90:vietbuild1&amp;catid=110&amp;lang=vi&amp;Itemid=588">
        Đọc thêm...</a>
</p>

<div class="item-separator"></div>