<div class="grid_3">
    <div class="moduletable  ml box pdb10 bgw">
        <div class="m-title">
            <h3>Danh mục sản phẩm</h3>

            <div class="modulcontent">
                <ul class="menu dotx">
                    <li class="item-492"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=83&amp;Itemid=492&amp;lang=vi">Ống
                            uPVC</a></li>
                    <li class="item-493"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=84&amp;Itemid=493&amp;lang=vi">Ống
                            HDPE</a></li>
                    <li class="item-658"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=319&amp;Itemid=658&amp;lang=vi">Ống
                            PPR</a></li>
                    <li class="item-494 deeper parent"><a
                            href="/index.php?option=com_adsmanager&amp;view=list&amp;catid=9&amp;Itemid=494&amp;lang=vi">Phụ
                            kiện uPVC</a>
                        <ul>
                            <li class="item-636"><a
                                    href="/index.php?option=com_adsmanager&amp;view=list&amp;catid=34&amp;Itemid=636&amp;lang=vi">Tiêu
                                    Chuẩn ASTM</a></li>
                            <li class="item-650"><a
                                    href="/index.php?option=com_adsmanager&amp;view=list&amp;catid=28&amp;Itemid=650&amp;lang=vi">Tiêu
                                    Chuẩn ISO</a></li>
                        </ul>
                    </li>
                    <li class="item-597"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=318&amp;Itemid=597&amp;lang=vi">Phụ
                            kiện HDPE</a></li>
                    <li class="item-656"><a
                            href="/index.php?option=com_content&amp;view=article&amp;id=321&amp;Itemid=656&amp;lang=vi">Phụ
                            kiện PPR</a></li>
                    <li class="item-598"><a
                            href="/index.php?option=com_adsmanager&amp;view=list&amp;catid=22&amp;Itemid=598&amp;lang=vi">Phụ
                            kiện khác</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="moduletable  ml top15">
        <div class="m-title">
            <h3>Thành tựu nổi bật</h3>

            <div class="modulcontent">
                <script language="JavaScript1.2">
                    var IHRSS_WIDTH = "215px";
                    var IHRSS_HEIGHT = "280px";
                    var IHRSS_SPEED = 1;
                    var IHRSS_BGCOLOR = "#FFFFFF";
                    var IHRSS_SLIDESRARRAY = new Array();
                    var IHRSS_FINALSLIDE = '';
                    IHRSS_SLIDESRARRAY[0] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//T101.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[1] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t161.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[2] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t01.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[3] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//T100.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[4] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//1002.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[5] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t141.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[6] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//1001.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[7] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t171.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[8] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//T10.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[9] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t121.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[10] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//1003.jpg" /></a>';
                    IHRSS_SLIDESRARRAY[11] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t131.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[12] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t181.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[13] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//t991.jpg.puk" /></a>';
                    IHRSS_SLIDESRARRAY[14] = '<a href="#"><img src="http://nhuadenhat.vn/images/bangkhen//1000.jpg" /></a>';
                    var IHRSS_IMGGAP = " ";
                    var IHRSS_PIXELGAP = 5;
                </script>
                <script
                    src="/modules/mod_horizontal_scrolling_slideshow/tmpl/mod_horizontal_scrolling_slideshow.js"
                    type="text/javascript"></script>
                        <span id="temp" style="visibility:hidden;position:absolute;top:-100px;left:-9000px"><nobr><a
                                    href="#"><img src="http://nhuadenhat.vn/images/bangkhen//T101.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t161.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t01.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//T100.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//1002.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t141.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//1001.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t171.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//T10.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t121.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//1003.jpg"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t131.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t181.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//t991.jpg.puk"></a> <a href="#"><img
                                        src="http://nhuadenhat.vn/images/bangkhen//1000.jpg"></a></nobr></span>
                <table border="0" cellspacing="0" cellpadding="0">
                    <tbody>
                    <tr>
                        <td>
                            <div style="position:relative;width:215px;height:280px;overflow:hidden">
                                <div style="position:absolute;width:215px;height:280px;background-color:#FFFFFF"
                                     onmouseover="copyspeed=0" onmouseout="copyspeed=IHRSS_SPEED">
                                    <div id="test2" style="position: absolute; left: -371px; top: 0px;">
                                        <nobr><a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T101.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t161.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t01.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T100.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1002.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t141.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1001.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t171.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T10.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t121.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1003.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t131.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t181.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t991.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1000.jpg"></a>
                                        </nobr>
                                    </div>
                                    <div id="test3" style="position: absolute; left: 2701px; top: 0px;">
                                        <nobr><a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T101.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t161.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t01.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T100.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1002.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t141.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1001.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t171.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//T10.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t121.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1003.jpg"></a> <a
                                                href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t131.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t181.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//t991.jpg.puk"></a>
                                            <a href="#"><img
                                                    src="http://nhuadenhat.vn/images/bangkhen//1000.jpg"></a>
                                        </nobr>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="moduletable  ml pdb10">
        <div class="m-title">
            <h3>Tin tức</h3>

            <div class="modulcontent">
                <ul class="menu dotx">
                    <li class="item-507"><a
                            href="/index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=110&amp;Itemid=507&amp;lang=vi">Tin
                            tức nội bộ</a></li>
                    <li class="item-508"><a
                            href="/index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=111&amp;Itemid=508&amp;lang=vi">Tin
                            tức báo chí</a></li>
                    <li class="item-509"><a
                            href="/index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=112&amp;Itemid=509&amp;lang=vi">Bài
                            viết nghiên cứu</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
&nbsp;
<div class="grid_9 fix-right-content">
    &nbsp;


    <div class=" bgw">

        <div id="system-message-container">
        </div>


        <div class="blog LatestAds">
            <div class="m-title">
                <h3>Network</h3>

            </div>
            <form action="/index.php?option=com_helloworld&amp;view=helloworld&amp;Itemid=590&amp;lang=vi" method="post" name="adminForm">
                <div class="filter-bar">
                    <div class="filter-input fl none">
                        <label class="filter-search-lbl" for="filter_search">Đại lý:</label>
                        <input type="text" name="filter_search" id="filter_search" value="" title="COM_USERS_SEARCH_USERS">
                        <button type="submit">Tìm kiếm</button>
                        <button type="button" onclick="document.id('filter_search').value='';this.form.submit();">Nhập lại</button>

                    </div>
                    <div class="filter-select fr">
                        <select name="filter_provinces" class="inputbox" onchange="this.form.submit()">
                            <option value="*">Tỉnh Thành</option>
                            <option value="8">TP HCM</option>
                            <option value="25">Hà Nội</option>
                            <option value="66">Đà Nẵng</option>
                            <option value="29">Hải Phòng</option>
                            <option value="5">Bắc Cạn</option>
                            <option value="6">Bắc Giang</option>
                            <option value="7">Cà Mau</option>
                            <option value="2">Thừa Thiên Huế</option>
                            <option value="9">Bình Dương</option>
                            <option value="10">Bình Định</option>
                            <option value="11">Bình Phước</option>
                            <option value="12">Bình Thuận</option>
                            <option value="13">Bến Tre</option>
                            <option value="14">Cao Bằng</option>
                            <option value="15">Cần Thơ</option>
                            <option value="3">Bà Rịa - Vũng Tàu</option>
                            <option value="17">Đắc Lắk</option>
                            <option value="18">Đắc Nông</option>
                            <option value="19">Điện Biên</option>
                            <option value="20">Đồng Nai</option>
                            <option value="21">Đồng Tháp</option>
                            <option value="22">Gia Lai</option>
                            <option value="23">Hà Giang</option>
                            <option value="24">Hà Nam</option>
                            <option value="27">Hà Tỉnh</option>
                            <option value="28">Hải Dương</option>
                            <option value="4">Bạc Liêu</option>
                            <option value="30">Hậu Giang</option>
                            <option value="31">Hòa Bình</option>
                            <option value="32">Hưng Yên</option>
                            <option value="33">Khánh Hòa</option>
                            <option value="34">Kiên Giang</option>
                            <option value="35">Kon Tum</option>
                            <option value="36">Lai Châu</option>
                            <option value="37">Lâm Đồng</option>
                            <option value="38">Lạng Sơn</option>
                            <option value="39">Lào Cai</option>
                            <option value="40">Long An</option>
                            <option value="41">Nam Định</option>
                            <option value="42">Nghệ An</option>
                            <option value="43">Ninh Bình</option>
                            <option value="44">Ninh Thuận</option>
                            <option value="45">Phú Thọ</option>
                            <option value="46">Phú Yên</option>
                            <option value="47">Quảng Bình</option>
                            <option value="48">Quảng Nam</option>
                            <option value="49">Quảng Ngãi</option>
                            <option value="50">Quảng Ninh</option>
                            <option value="51">Quảng Trị</option>
                            <option value="52">Sóc Trăng</option>
                            <option value="53">Sơn La</option>
                            <option value="54">Tây Ninh</option>
                            <option value="55">Thái Bình</option>
                            <option value="56">Thái Nguyên</option>
                            <option value="57">Thanh Hóa</option>
                            <option value="58">An Giang</option>
                            <option value="59">Tiền Giang</option>
                            <option value="60">Bắc Ninh</option>
                            <option value="61">Trà Vinh</option>
                            <option value="62">Tuyên Quang</option>
                            <option value="63">Vĩnh Long</option>
                            <option value="64">Vĩnh Phúc</option>
                            <option value="65">Yên Bái</option>
                        </select>
                        <select name="filter_district" class="inputbox" onchange="this.form.submit()">
                            <option value="*">Quận huyện</option>

                        </select>
                    </div>
                </div>
                <div class="box box-daily fl">
                    <h3 class="title_network">Hệ thống mạng lưới</h3>
                    <table class="zebra" width="100%">
                        <thead>
                        <tr>
                            <th>Stt</th>
                            <th>Đại lý</th>
                            <th>Địa chỉ</th>
                            <th>Điện thoại</th>
                            <th>Fax</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>1</td>
                            <td>CTY TNHH MTV TM THANH DUNG</td>
                            <td>A8/16 Ấp 1, Thanh Niên, Lê Minh Xuân, Quận Tân Bình, TP HCM.</td>
                            <td>(08).39716373</td>
                            <td>(08).38651917</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>CTY TNHH DV SÁU ẨN</td>
                            <td>12R-334 Tô Hiến Thành, phường 14, Quận 10, TP HCM.</td>
                            <td>(08).35070013</td>
                            <td>(08).38639607</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>CTY TNHH  HOÀNG MINH ANH</td>
                            <td>B1, KP4, đường Đồng  Khởi, P. Tân Hiệp, Tp.Biên Hoà, Đồng Nai.</td>
                            <td>(061).3895.797</td>
                            <td>(061).3895.797</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>CTY TNHH SX- TM - DV  VÂN THIÊN </td>
                            <td>93- KP2, Võ Văn Ngân, P. Linh Chiểu, Quận Thủ Đức, TP HCM.</td>
                            <td>(08).37222.464</td>
                            <td>(08).37.220.454</td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>DOANH  NGHIỆP TƯ NHÂN  VI VI </td>
                            <td>KP6, P.Tân Biên, Tp.Biên Hoà, Đồng Nai.</td>
                            <td>(061).3881.260</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>CTY TNHH XUẤT NHẬP KHẨU  LỮ NAM </td>
                            <td>286 đường số 1, KP 7, P.Bình Trị Đông, Quận Bình Tân, TP HCM.</td>
                            <td>(08).62.602.229</td>
                            <td>(08).62.602.002</td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td>CTY TNHH  AN NHẬT HÀ </td>
                            <td>189 Nguyễn Thái Bình. P.3, Tp.Tân An, Long An.</td>
                            <td>723.513.870</td>
                            <td>726.251.012</td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td>CTY TNHH HOÀNG TÍN</td>
                            <td>QL5, An Đồng 1, An Dương, Q.Dương Kinh, Hải Phòng.</td>
                            <td>0313 513 835</td>
                            <td>0313 783 654</td>
                        </tr>
                        <tr>
                            <td>9</td>
                            <td>CTY CP TAM ĐA</td>
                            <td>87 Bà Triệu, Cẩm Đông, Tp.Hạ Long, Quảng Ninh.</td>
                            <td>0333 711 978</td>
                            <td>0333 723 468</td>
                        </tr>
                        <tr>
                            <td>10</td>
                            <td>CTY CP AN ĐẠT</td>
                            <td>Số 7, Ngõ 51/2, Phố Lãng Yên, Q.Hai Bà Trưng, Hà Nội.</td>
                            <td>043 9715 851</td>
                            <td>043 6741 010</td>
                        </tr>
                        <tr>
                            <td>11</td>
                            <td>CTY TNHH QUẢNG CÁO VÀ TM PHÚC LỘC</td>
                            <td>236 Trần Hưng Đạo, Tiến An, Tp.Bắc Ninh, Bắc Ninh.</td>
                            <td>0241 3898 897</td>
                            <td>0241 3898 899</td>
                        </tr>
                        <tr>
                            <td>12</td>
                            <td>CTY TNHH TM THANH MƠ</td>
                            <td>263 Trường Chinh, P. Khương Mai, Q.Thanh Xuân, Hà Nội.</td>
                            <td>043 8532 454</td>
                            <td>043 5638 229</td>
                        </tr>
                        <tr>
                            <td>13</td>
                            <td>DNTN TM ĐÔNG NAM</td>
                            <td>Tiền Trung,. Ái Quốc, Tp.Hải Dương, Hải Dương.</td>
                            <td>03203 753 266</td>
                            <td>03203 753 322</td>
                        </tr>
                        <tr>
                            <td>14</td>
                            <td>CTY TNHH MTV THANH DUNG</td>
                            <td>44A Lê Hồng Phong, Tp.Nha Trang, Khánh Hòa.</td>
                            <td>058.3877878</td>
                            <td>058.3877373</td>
                        </tr>
                        <tr>
                            <td>15</td>
                            <td>DNTN HOÀNG THỨC</td>
                            <td>02 Vũ Bảo, TP.Quy Nhơn, Bình Định.</td>
                            <td>056.3521337</td>
                            <td>056.3521309</td>
                        </tr>
                        <tr>
                            <td>16</td>
                            <td>CỬA HÀNG CHÂN THANH</td>
                            <td>47 Hai Bà Trưng, H.Đức Trọng, Lâm Đồng.</td>
                            <td>063.3843104</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>17</td>
                            <td>CTY TNHH XD- TM &amp; DV TRƯỜNG HUY PHÁT</td>
                            <td>55 Đinh Tiên Hoàng, Tp.Pleiku, Gia Lai.</td>
                            <td>059.3719277</td>
                            <td>059.3720.137</td>
                        </tr>
                        <tr>
                            <td>18</td>
                            <td>CTY TNHH TM&amp;DV  MINH NGHI</td>
                            <td>153 A, đường 30/4, P. Hưng Lợi, Q.Ninh Kiều, Cần Thơ.</td>
                            <td>07106.250.194</td>
                            <td>07106.250.195</td>
                        </tr>
                        <tr>
                            <td>19</td>
                            <td>CTY TNHH TM&amp;DV  AN KHÁNH</td>
                            <td>74A4 Cao Thắng, P. Bình Khánh, TP.Long Xuyên, An Giang.</td>
                            <td>0763.989.992</td>
                            <td>0763.989.991</td>
                        </tr>
                        <tr>
                            <td>20</td>
                            <td>CTY TNHH MTV  VĨNH THỐNG</td>
                            <td>Số 2S đường Hùng Vương, P.1, Tp.Vĩnh Long, Vĩnh Long.</td>
                            <td>0703.877.536</td>
                            <td>0703.877.536</td>
                        </tr>
                        <tr>
                            <td>21</td>
                            <td>CTY CPVLXD BẾN TRE</td>
                            <td>Số 207D Nguyễn Đình Chiểu, Xã Phú Hưng, Tp.Bến Tre, Bến Tre.</td>
                            <td>075.822.315</td>
                            <td>075.822319</td>
                        </tr>
                        <tr>
                            <td>22</td>
                            <td>CTY TNHH DV&amp;TM MỸ THÀNH</td>
                            <td>Số 110/61A Phạm Ngũ Lão, Khóm 3, P.1, Tp.Trà Vinh, Trà Vinh.</td>
                            <td>074. 3850.877</td>
                            <td>074. 3850.897</td>
                        </tr>
                        <tr>
                            <td>23</td>
                            <td>CTY TNHH MTV TM-DV ĐIỆN- ĐIỆN LẠNH THÀNH LỘC</td>
                            <td>Soá 12/11 Lê Hồng Phong, Phường Bình Thủy, Q.Bình Thuỷ, Cần Thơ.</td>
                            <td>0710.625.1223</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>24</td>
                            <td>CTY TNHH THẢO HIẾU</td>
                            <td>86 Lê Phụng Hiểu, Q.Cẩm Lệ, Đà Nẵng.</td>
                            <td>05113 911452</td>
                            <td>05113 911452</td>
                        </tr>
                        <tr>
                            <td>25</td>
                            <td>CÔNG TY TNHH SẢN XUẤT VÀ THƯƠNG MẠI PHÚC HƯNG</td>
                            <td>137 Huỳnh Thúc Kháng, Tp.Huế, Thừa Thiên Huế.</td>
                            <td>0543 512137</td>
                            <td>0543 531 375</td>
                        </tr>
                        <tr>
                            <td>26</td>
                            <td>CÔNG TY TNHH YÊN LOAN</td>
                            <td>95A QL9, Tp.Đông Hà, Quảng Trị.</td>
                            <td>0533 555999</td>
                            <td>0533 564388</td>
                        </tr>
                        <tr>
                            <td>27</td>
                            <td>CÔNG TY TNHH THÁI HOÀ</td>
                            <td>04 Lê Quý Đôn, Tp.Đồng Hới, Quảng Bình.</td>
                            <td>0523 828114</td>
                            <td>0523 850774</td>
                        </tr>
                        <tr>
                            <td>28</td>
                            <td>CÔNG TY TNHH QUẾ HÀ</td>
                            <td>188 Phan Đình Phùng, Tp.Vinh, Nghệ An.</td>
                            <td>0383 843881</td>
                            <td>038 6253499</td>
                        </tr>
                        <tr>
                            <td>29</td>
                            <td>HUYNH ĐỆ</td>
                            <td>136/6 Huỳnh Hữu Thống, P.3, Tp.Tân An, Long An.</td>
                            <td>(072) 3500567</td>
                            <td>(072) 3825 211</td>
                        </tr>
                        <tr>
                            <td>30</td>
                            <td>NGUYỄN ĐÌNH</td>
                            <td>28/3A, Tổ 7, KP Bình Giao,  P. Thuận giao, Q.Thuận An, Bình Dương.</td>
                            <td>(0650) 3717 606</td>
                            <td>(08) 542 26 242</td>
                        </tr>
                        <tr>
                            <td>31</td>
                            <td>MAI TIẾN PHÁT</td>
                            <td>31 Đường 14, P. An Bình, Quận 2, TP HCM.</td>
                            <td>(08)2221 2619 </td>
                            <td>(08)62607186</td>
                        </tr>
                        <tr>
                            <td>32</td>
                            <td>PHƯỢNG HOÀNG</td>
                            <td>240 XVNT, P.21, Quận Bình Thạnh, TP HCM.</td>
                            <td>(08) 35 142 909</td>
                            <td>(08) 38 035 671</td>
                        </tr>
                        <tr>
                            <td>33</td>
                            <td>SÁU HẠNH</td>
                            <td>346 Phạm Hữu Lầu, Ấp 4, P. Phước Kiển, H.Nhà Bè, TP HCM.</td>
                            <td>(08) 3781 7836</td>
                            <td>08) 3781 7920</td>
                        </tr>
                        <tr>
                            <td>34</td>
                            <td>VÕ HẢI DƯƠNG</td>
                            <td>Số 13 Đường 7, P. An Lạc A, Quận Bình Tân, TP HCM.</td>
                            <td>(08) 3751 7977</td>
                            <td>(08) 3701 8034</td>
                        </tr>
                        <tr>
                            <td>35</td>
                            <td>KHÁNH TRƯỜNG</td>
                            <td>35/4 ấp Quảng Đà, Xã Đông Hòa, H.Trảng Bom, Đồng Nai.</td>
                            <td>(061)3.768 002</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>36</td>
                            <td>HÀ NAM</td>
                            <td>195A Nguyễn Thị Thập, P. Tân Phú, Quận 7, TP HCM.</td>
                            <td>08)3.7751228  </td>
                            <td>(08)05 433 1844</td>
                        </tr>
                        <tr>
                            <td>37</td>
                            <td>LÝ GIA PHÁT </td>
                            <td>8/2 Bình Phú, Bình Chuẩn, Q.Thuận An, Bình Dương.</td>
                            <td>0650) 3827 050 </td>
                            <td>(0650) 3798 235</td>
                        </tr>
                        <tr>
                            <td>38</td>
                            <td>DUYÊN</td>
                            <td>281 Xô Viết Nghệ Tĩnh, P.15 , Quận Bình Thạnh, TP HCM.</td>
                            <td>08.3899.3293</td>
                            <td>08.350 112.884</td>
                        </tr>
                        <tr>
                            <td>39</td>
                            <td>TÂN TÙNG NAM</td>
                            <td>142 Hiệp Bình, P. Hiệp Bình Chánh, Quận Thủ Đức, TP HCM.</td>
                            <td>08-35542030</td>
                            <td>08-35542024</td>
                        </tr>
                        <tr>
                            <td>40</td>
                            <td>SIÊU CƯỜNG</td>
                            <td>27 Lê Quý Đôn, P.Phước Trung, Tx Bà Rịa, Bà Rịa - Vũng Tàu.</td>
                            <td>64.3826388</td>
                            <td>64.3717838</td>
                        </tr>
                        <tr>
                            <td>41</td>
                            <td>CÔNG TY CP TAM ĐA</td>
                            <td>311 Nguyễn Xiển, Thanh Xuân, Hà Nội, Q.Thanh Xuân, Hà Nội.</td>
                            <td>0433119568</td>
                            <td>0435590383</td>
                        </tr>
                        <tr>
                            <td>42</td>
                            <td>HOÀNG TÍN</td>
                            <td>Phòng 702, toà nhà CT3A Mễ Trì Thượng, Từ Liêm, Hà Nội, H.Từ Liêm, Hà Nội.</td>
                            <td>0437852757</td>
                            <td>0437852558</td>
                        </tr>
                        <tr>
                            <td>43</td>
                            <td>Công ty TNHH XD SX TM DV LAN THANH</td>
                            <td>665A Kinh Dương Vương, P. An Lạc, Quận Bình Tân, TP HCM.</td>
                            <td>08.3752 6262</td>
                            <td>08.3752 0329</td>
                        </tr>
                        </tbody>

                    </table>
                </div>
            </form>
        </div>

    </div>

</div>