<!DOCTYPE html>
<html lang="en">
<head>
    <title><?=$this->translate($this->title)?></title>
    <meta http-equiv="Content-Type" content="text/html;_ISO">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- mobile viewport -->

    <script type="text/javascript" src="/templates/templatename/js/template.js.php?b=0&amp;v=1"
            style="color: rgb(0, 0, 0);"></script>

    <link type="text/css" href="templates/templatename/css/template_css.css" rel="stylesheet">
    <link type="text/css" href="templates/templatename/css/add_css.css" rel="stylesheet">
    <link type="text/css" href="templates/templatename/css/tools.css" rel="stylesheet">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="keywords" content="vi-VN, Việt Nam">
    <meta name="description" content="Ngôn ngữ tiếng việt, Ngôn ngữ">
    <link href="index.php?format=feed&amp;type=rss&amp;lang=vi" rel="alternate" type="application/rss+xml"
          title="RSS 2.0">
    <link href="index.php?format=feed&amp;type=atom&amp;lang=vi" rel="alternate" type="application/atom+xml"
          title="Atom 1.0">
    <link href="templates/templatename/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
    <link href="http://nhuadenhat.vn/index.php?option=com_search&amp;format=opensearch&amp;lang=vi" rel="search"
          title="tìm kiếm" type="application/opensearchdescription+xml">
    <link rel="stylesheet" href="media/system/css/modal.css" type="text/css">
    <link rel="stylesheet" href="templates/templatename/css/template.css.php?b=0&amp;v=1" type="text/css">
    <link rel="stylesheet" href="media/mod_vvisit_counter/digit_counter/default.css" type="text/css">
    <link rel="stylesheet" href="media/mod_vvisit_counter/stats/default.css" type="text/css">
    <link rel="stylesheet" href="http://nhuadenhat.vn/components/com_adsmanager/css/adsmanager.css" type="text/css">
    <link rel="stylesheet"
          href="http://nhuadenhat.vn/components/com_adsmanager/css/ui-lightness/jquery-ui-1.8.16.custom.css"
          type="text/css">
    <link rel="stylesheet" href="modules/mod_AutsonSlideShow/css/skitter.css" type="text/css">
    <link rel="stylesheet" href="media/mod_languages/css/template.css" type="text/css">
    <script src="media/system/js/modal.js" type="text/javascript"></script>
    <script src="http://nhuadenhat.vn/components/com_adsmanager/js/jquery-1.6.2.min.js" type="text/javascript"></script>
    <script src="http://nhuadenhat.vn/components/com_adsmanager/js/noconflict.js" type="text/javascript"></script>
    <script src="http://nhuadenhat.vn/components/com_adsmanager/js/jquery-ui-1.8.16.custom.min.js"
            type="text/javascript"></script>
    <link rel="apple-touch-icon-precomposed" href="templates/templatename/apple-touch-icon-57x57.png">
    <!-- iphone, ipod, android -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="templates/templatename/apple-touch-icon-72x72.png">
    <!-- ipad -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="templates/templatename/apple-touch-icon-114x114.png">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <!-- Latest compiled and minified JavaScript -->
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <link rel="stylesheet" href="css/customApplication.css">
    <script src="js/customApplication.js"></script>


    <link rel="stylesheet" href="css/flickity.css">
    <script src="js/flickity.pkgd.min.js"></script>
</head>

<body class=" fix-body">
<div class="container_12">
<div class="grid_12 header fix_header">

    <ul class="menu" id="topbar">
        <li class="item-593">
            <a href="<?=$this->basePath('Sitemap')?>">
                <img src="images/ico-menu/sitemap.png" alt="<?=$this->translate('Sitemap')?>">
                <span class="image-title"><?=$this->translate('Sitemap')?></span>
            </a>
        </li>
        <li class="item-594">
            <a href="<?=$this->basePath('Contact')?>">
                <img src="images/ico-menu/contact.png" alt="<?=$this->translate('Contact')?>">
                <span class="image-title"><?=$this->translate('Contact')?></span>
            </a>
        </li>
    </ul>
    <div class="mod-languages">
        <ul class="lang-block">
            <li class="lang-active" dir="ltr">
                <a><img src="media/mod_languages/images/vi.gif" alt="vietnam" title="vietnam"> </a>
            </li>
        </ul>
    </div>

    <div class="custom fl">
        <div class="logo_swf">
            <object width="600" height="100" data="images/logo/logo.swf" type="application/x-shockwave-flash">
                <param name="src" value="images/logo/logo.swf">
                <param name="wmode" value="transparent">
            </object>
        </div>
        <h1 style="position: absolute; top: -10000px; overflow: auto;"><strong><em> <a
                        href="http://taigamevuabai.com/tai-game-vua-bai-xi-ngau-thau-bac-ty/" target="_blank"
                        title="Tải game vua bài – Đổ xí ngầu thâu bạc tỷ">Tải game vua bài – Đổ xí ngầu thâu bạc
                        tỷ</a> <a href="http://tai-bigone.org/huong-dan-choi-binh-trong-game-bigone/"
                                  target="_blank" title="Hướng Dẫn Chơi Binh Trong Game Bigone">Hướng Dẫn Chơi Binh
                        Trong Game Bigone</a> <a href="http://hoangphatcamera.com/lap-dat-camera-quan-sat.html"
                                                 target="_blank" title="lap dat camera quan sat">lap dat camera quan
                        sat</a> <a href="http://hoangphatcamera.com/lap-dat-camera-quan-sat.html" target="_blank"
                                   title="dịch vụ lắp đặt camera quan sát">dịch vụ lắp đặt camera quan sát</a> <a
                        href="http://hoangphatcamera.com/lap-dat-camera-quan-sat.html" target="_blank"
                        title="lắp đặt camera giám sát">lắp đặt camera giám sát</a> </em></strong></h1></div>

</div>
<div class="clr"></div>

<div class="grid_12 navi">

    <ul class="menu menu-main menu_vn" id="menu-main">
        <?php foreach($this->menus as $menu): ?>
            <li class="<?=$menu['class']?> <?=$menu['classActive']?>">
                <a href="<?=$this->basePath(strtolower($menu['name']))?>"><?=$this->translate($menu['name'])?></a>
            </li>
        <?php endforeach ?>
    </ul>

    <div id="intro-bar" class="fl intro-bar">
        <div class="fl left15 intro-bar-left"><span><?=$this->translate('Welcome to First Chemical Plastic Co.')?></span></div>
        <div class="fr right15 intro-bar-right"><em><span>

            Tp.HCM ngày <?=date('d')?> tháng <?=date('m')?> năm <?=date('y')?>

            </span></em></div>
    </div>
</div>
<div class="clr"></div>


<div class="grid_12">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.3/jquery.min.js" type="text/javascript"></script>

    <div class="joomla_ass fl" align="left">

        <div class="border_box">

            <div class="box_skitter box_skitter_large126">

                <div id="carousel-slider-image" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-slider-image" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-slider-image" data-slide-to="1"></li>
                        <li data-target="#carousel-slider-image" data-slide-to="2"></li>
                        <li data-target="#carousel-slider-image" data-slide-to="3"></li>
                        <li data-target="#carousel-slider-image" data-slide-to="4"></li>
                        <li data-target="#carousel-slider-image" data-slide-to="5"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="images/slide/1.jpg" alt="...">
                            <div class="carousel-caption">

                            </div>
                        </div>
                        <div class="item">
                            <img src="images/slide/n1.jpg" alt="...">
                            <div class="carousel-caption">

                            </div>
                        </div>
                        <div class="item">
                            <img src="images/slide/n2.jpg" alt="...">
                            <div class="carousel-caption">

                            </div>
                        </div>
                        <div class="item">
                            <img src="images/slide/n3.jpg" alt="...">
                            <div class="carousel-caption">

                            </div>
                        </div>
                        <div class="item">
                            <img src="images/slide/2.jpg" alt="...">
                            <div class="carousel-caption">

                            </div>
                        </div>
                        <div class="item">
                            <img src="images/slide/4.png" alt="...">
                            <div class="carousel-caption">

                            </div>
                        </div>

                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-slider-image" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-slider-image" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

        </div>

    </div>


</div>
<div class="clr"></div>

<div class="grid_12 home-about">
    <div class="moduletable ">
        <div class="m-title">
            <div class="modulcontent">

                <div class="custom">
                    <div class="intro-page"><img src="images/intro-page/m2.jpg" border="0" alt=""
                                                 style="float: left;">

                        <div class="about-body">
                            <h3>Giới thiệu công ty</h3>

                            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <strong>Công ty Trách Nhiệm Hữu Hạn Hóa Nhựa Đệ Nhất</strong> được thành lập vào năm
                                1994, là đơn vị liên doanh giữa Công ty Công Nghiệp Nhựa TaYing (Đài Loan) và Công
                                ty TNHH TM Sản Xuất Hiệp Hưng (Việt Nam). Được cấp Giấy phép hoạt động số:
                                502022000066. <a class="readmore"
                                                 href="index.php?option=com_content&amp;view=article&amp;id=75&amp;Itemid=586&amp;lang=vi">Xem
                                    thêm</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<div class="grid_12 fix-content">
    <?=$this->content?>
</div>
<div class="clr"></div>

<!-- Flickity HTML init -->
<div class="gallery js-flickity" data-flickity-options='{ "freeScroll": true, "wrapAround": true }'>
    <!-- images from unsplash.com -->
    <div class="gallery-cell">
        <img src="images/bangkhen/1000.jpg" class="img-responsive" alt="orange tree" />
    </div>
    <div class="gallery-cell">
        <img src="images/bangkhen/1001.jpg" class="img-responsive" alt="submerged" />
    </div>
    <div class="gallery-cell">
        <img src="images/bangkhen/1002.jpg" class="img-responsive" alt="look-out" />
    </div>
    <div class="gallery-cell">
        <img src="images/bangkhen/T100.jpg" class="img-responsive" alt="look-out" />
    </div>
    <div class="gallery-cell">
        <img src="images/bangkhen/T101.jpg" class="img-responsive" alt="look-out" />
    </div>
</div>


<div class="footer2">

    <ul class="menu menuFooter" id="menuFooter">
        <?php foreach($this->menus as $menu): ?>
            <li class="<?=$menu['class']?> <?=$menu['classActive']?>">
                <a href="<?=$this->basePath(strtolower($menu['name']))?>"><?=$this->translate($menu['name'])?></a>
            </li>
        <?php endforeach ?>
    </ul>

    <br>

    <div class="customlogofooter">
        <p style="text-align: center;"><strong>CÔNG TY TNHH HÓA NHỰA ĐỆ NHẤT</strong><br><span>75-77,Caltmete ,P.Nguyễn Thái Bình, Quận 1, TP Hồ Chí Minh</span><br>Điện
            thoại: (08).62915599 - Fax: (08).62915598 - Email: cntphcm@nhuadenhat.vn - Website: <a href="index.php">www.nhuadenhat.vn</a>
        </p>
    </div>
</div>
    <div class="list-group-item"></div>
<div class="clr"></div>

</div>

<code><!-- Vinaora Visitors Counter >> http://vinaora.com/ -->
    <script>
        $(document).ready(function () {

            // hide #back-top first
            $("#back-top").hide();

            // fade in #back-top
            $(function () {
                $(window).scroll(function () {
                    if ($(this).scrollTop() > 100) {
                        $('#back-top').fadeIn();
                    } else {
                        $('#back-top').fadeOut();
                    }
                });

                // scroll body to 0px on click
                $('#back-top a').click(function () {
                    $('body,html').animate({
                        scrollTop: 0
                    }, 800);
                    return false;
                });
            });

        });
    </script>
    <p id="back-top" class="back-top" style="display: none;">
        <a href="#top"><span></span></a>
    </p>
</code>

<div class="clr"></div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins)-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!--Include all compiled plugins (below), or include individual files as needed-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script>
    var basePath = '<?=$this->basePath()?>';
</script>
<script src="js/news.js"></script>
</body>
</html>

<?php $this->translate('Home')?>
<?php $this->translate('Introduction')?>
<?php $this->translate('Product')?>
<?php $this->translate('News')?>
<?php $this->translate('Project')?>
<?php $this->translate('Network')?>
<?php $this->translate('Quotes')?>
<?php $this->translate('Sitemap')?>
<?php $this->translate('Contact')?>
